openapi: 3.0.0
info:
  title: KU Talai API
  description: To be added
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/talai-api/v1
paths:
  /busstops:
    get:
      summary: Returns list of Talai bus stops in KU
      operationId: controller.get_busstops
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Busstop'
  /busstop/{stopId}:
    parameters:
      - name: stopId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns complete details of the specified Talai bus stop
      operationId: controller.get_busstop
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Busstop'
  /busstop/{stopId}/weather:
    parameters:
      - name: stopId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns weather detail of the specified Talai bus stop
      operationId: controller.get_busstop_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusstopWeather'

components:
  schemas:
    Busstop:
      type: object
      properties:
        busstopId:
          type: integer
        name:
          type: string
        lat:
          type: number
        lon:
          type: number
    BusRoute:
      type: object
      properties:
        routeId:
          type: integer
        busId:
          type: integer
    BusstopWeather:
      type: object
      properties:
        busstopId:
          type: integer
        timestamp:
          type: string
        amount:
          type: number
