openapi: 3.0.0
info:
  title: KU Talai API
  description: To be added
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/talai-api/v1
paths:
  /busstops:
    get:
      summary: Returns list of Talai bus stops in KU
      operationId: controller.get_busstops
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Busstop'
  /busstop/{stopId}:
    parameters:
      - name: stopId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns complete details of the specified Talai bus stop
      operationId: controller.get_busstop
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Busstop'
  /busstop/{stopId}/weather:
    parameters:
      - name: stopId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns weather detail of the specified Talai bus stop
      operationId: controller.get_busstop_weather
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusstopWeather'
  /routes:
    get:
      summary: Returns a list of routes of KU Talai bus
      operationId: controller.get_routes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
  /bus/{stopIdOrigin}/{stopIdDest}:
    parameters:
      - name: stopIdOrigin
        in: path
        required: true
        schema:
          type: integer
      - name: stopIdDest
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns list of takable bus from origin to destination
      operationId: controller.get_takable_bus
      responses:
        200:
          description: Success
  /route/{busId}:
    parameters:
      - name: busId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns all bus stops for given route
      operationId: controller.get_bus_route
      responses:
        200:
          description: Success
  /buses:
    get:
      summary: Returns all KU Talai bus number
      operationId: controller.get_buses
      responses:
        200:
          description: Success
  /population/{stopId}:
    parameters:
      - name: stopId
        in: path
        required: true
        schema:
          type: integer
    put:
      summary: Increment people in KU Talai bus stop
      operationId: controller.put_population
      responses:
        200:
          description: Success
    get:
      summary: Get population density in each KU Talai bus
      operationId: controller.get_population
      responses:
        200:
          description: Success

components:
  schemas:
    Busstop:
      type: object
      properties:
        busstopId:
          type: integer
        name:
          type: string
        lat:
          type: number
        lon:
          type: number
    Route:
      type: object
      properties:
        id:
          type: integer
        routeNumber:
          type: integer
        name:
          type: string
    Bus:
      type: object
      properties:
        id:
          type: object
        bus_number:
          type: integer
        bus_stop_id:
          type: integer
        route_id:
          type: integer
    BusstopWeather:
      type: object
      properties:
        busstopId:
          type: integer
        timestamp:
          type: string
        amount:
          type: number
