# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Bus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bus_number=None, bus_stops=None):  # noqa: E501
        """Bus - a model defined in OpenAPI

        :param bus_number: The bus_number of this Bus.  # noqa: E501
        :type bus_number: int
        :param bus_stops: The bus_stops of this Bus.  # noqa: E501
        :type bus_stops: List[int]
        """
        self.openapi_types = {
            'bus_number': int,
            'bus_stops': List[int]
        }

        self.attribute_map = {
            'bus_number': 'bus_number',
            'bus_stops': 'bus_stops'
        }

        self._bus_number = bus_number
        self._bus_stops = bus_stops

    @classmethod
    def from_dict(cls, dikt) -> 'Bus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Bus of this Bus.  # noqa: E501
        :rtype: Bus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bus_number(self):
        """Gets the bus_number of this Bus.


        :return: The bus_number of this Bus.
        :rtype: int
        """
        return self._bus_number

    @bus_number.setter
    def bus_number(self, bus_number):
        """Sets the bus_number of this Bus.


        :param bus_number: The bus_number of this Bus.
        :type bus_number: int
        """

        self._bus_number = bus_number

    @property
    def bus_stops(self):
        """Gets the bus_stops of this Bus.


        :return: The bus_stops of this Bus.
        :rtype: List[int]
        """
        return self._bus_stops

    @bus_stops.setter
    def bus_stops(self, bus_stops):
        """Sets the bus_stops of this Bus.


        :param bus_stops: The bus_stops of this Bus.
        :type bus_stops: List[int]
        """

        self._bus_stops = bus_stops
