# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BusstopWeather(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, busstop_id=None, timestamp=None, amount=None):  # noqa: E501
        """BusstopWeather - a model defined in OpenAPI

        :param busstop_id: The busstop_id of this BusstopWeather.  # noqa: E501
        :type busstop_id: int
        :param timestamp: The timestamp of this BusstopWeather.  # noqa: E501
        :type timestamp: str
        :param amount: The amount of this BusstopWeather.  # noqa: E501
        :type amount: float
        """
        self.openapi_types = {
            'busstop_id': int,
            'timestamp': str,
            'amount': float
        }

        self.attribute_map = {
            'busstop_id': 'busstopId',
            'timestamp': 'timestamp',
            'amount': 'amount'
        }

        self._busstop_id = busstop_id
        self._timestamp = timestamp
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'BusstopWeather':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BusstopWeather of this BusstopWeather.  # noqa: E501
        :rtype: BusstopWeather
        """
        return util.deserialize_model(dikt, cls)

    @property
    def busstop_id(self):
        """Gets the busstop_id of this BusstopWeather.


        :return: The busstop_id of this BusstopWeather.
        :rtype: int
        """
        return self._busstop_id

    @busstop_id.setter
    def busstop_id(self, busstop_id):
        """Sets the busstop_id of this BusstopWeather.


        :param busstop_id: The busstop_id of this BusstopWeather.
        :type busstop_id: int
        """

        self._busstop_id = busstop_id

    @property
    def timestamp(self):
        """Gets the timestamp of this BusstopWeather.


        :return: The timestamp of this BusstopWeather.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this BusstopWeather.


        :param timestamp: The timestamp of this BusstopWeather.
        :type timestamp: str
        """

        self._timestamp = timestamp

    @property
    def amount(self):
        """Gets the amount of this BusstopWeather.


        :return: The amount of this BusstopWeather.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this BusstopWeather.


        :param amount: The amount of this BusstopWeather.
        :type amount: float
        """

        self._amount = amount
