# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Route(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, route_number=None):  # noqa: E501
        """Route - a model defined in OpenAPI

        :param route_number: The route_number of this Route.  # noqa: E501
        :type route_number: int
        """
        self.openapi_types = {
            'route_number': int
        }

        self.attribute_map = {
            'route_number': 'routeNumber'
        }

        self._route_number = route_number

    @classmethod
    def from_dict(cls, dikt) -> 'Route':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Route of this Route.  # noqa: E501
        :rtype: Route
        """
        return util.deserialize_model(dikt, cls)

    @property
    def route_number(self):
        """Gets the route_number of this Route.


        :return: The route_number of this Route.
        :rtype: int
        """
        return self._route_number

    @route_number.setter
    def route_number(self, route_number):
        """Sets the route_number of this Route.


        :param route_number: The route_number of this Route.
        :type route_number: int
        """

        self._route_number = route_number
