openapi: 3.0.0
info:
  description: To be added
  title: KU Talai API
  version: 1.0.0
servers:
- url: http://127.0.0.1:8080/talai-api/v1
paths:
  /bus/{stopIdOrigin}/{stopIdDest}:
    get:
      operationId: controller_get_takable_bus
      parameters:
      - explode: false
        in: path
        name: stopIdOrigin
        required: true
        schema:
          type: integer
        style: simple
      - explode: false
        in: path
        name: stopIdDest
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Route'
                type: array
          description: Success
      summary: Returns list of takable bus from origin to destination
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /busstop/{stopId}:
    get:
      operationId: controller_get_busstop
      parameters:
      - explode: false
        in: path
        name: stopId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Busstop'
          description: Success
      summary: Returns complete details of the specified Talai bus stop
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /busstop/{stopId}/aqi:
    get:
      operationId: controller_get_busstop_aqi
      parameters:
      - explode: false
        in: path
        name: stopId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BusstopWeather'
                type: array
          description: Success
      summary: Returns PM2.5 detail of the specified Talai bus stop
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /busstop/{stopId}/temperature:
    get:
      operationId: controller_get_busstop_weather
      parameters:
      - explode: false
        in: path
        name: stopId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BusstopWeather'
                type: array
          description: Success
      summary: Returns weather detail of the specified Talai bus stop
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /busstops:
    get:
      operationId: controller_get_busstops
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Busstop'
                type: array
          description: Success
      summary: Returns list of Talai bus stops in KU
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /population/{stopId}:
    get:
      operationId: controller_get_population
      parameters:
      - explode: false
        in: path
        name: stopId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PopulationDensity'
                type: array
          description: Success
      summary: Get population density in each KU Talai bus
      x-openapi-router-controller: openapi_server.controllers.default_controller
    put:
      operationId: controller_put_population
      parameters:
      - explode: false
        in: path
        name: stopId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Success
      summary: Increment people in KU Talai bus stop
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /route/{busId}:
    get:
      operationId: controller_get_bus_route
      parameters:
      - explode: false
        in: path
        name: busId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bus'
          description: Success
      summary: Returns all bus stops for given route
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /routes:
    get:
      operationId: controller_get_routes
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Route'
                type: array
          description: Success
      summary: Returns a list of routes of KU Talai bus
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Busstop:
      example:
        busstopId: 0
        name: name
        lon: 1.4658129805029452
        lat: 6.027456183070403
      properties:
        busstopId:
          title: busstopId
          type: integer
        name:
          title: name
          type: string
        lat:
          title: lat
          type: number
        lon:
          title: lon
          type: number
      title: Busstop
      type: object
    Route:
      example:
        routeNumber: 0
      properties:
        routeNumber:
          title: routeNumber
          type: integer
      title: Route
      type: object
    Bus:
      example:
        bus_number: 0
        bus_stops:
        - 6
        - 6
      properties:
        bus_number:
          title: bus_number
          type: integer
        bus_stops:
          items:
            type: integer
          title: bus_stops
          type: array
      title: Bus
      type: object
    BusstopWeather:
      example:
        busstopId: 0
        amount: 6.027456183070403
        sensor: sensor
        timestamp: timestamp
      properties:
        busstopId:
          title: busstopId
          type: integer
        timestamp:
          title: timestamp
          type: string
        amount:
          title: amount
          type: number
        sensor:
          title: sensor
          type: string
      title: BusstopWeather
      type: object
    PopulationDensity:
      example:
        amount: 0
        timestamp: timestamp
      properties:
        timestamp:
          title: timestamp
          type: string
        amount:
          title: amount
          type: integer
      title: PopulationDensity
      type: object
