name: Check secrets

on:
  workflow_dispatch:

job:
  prepare:
    name: Prepare file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env file
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWD: ${{ secrets.DB_PASSWD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo $DB_HOST >> .env
          echo $DB_USER >> .env
          echo $DB_PASSWD >> .env
          echo $DB_NAME >> .env
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: .