name: Insert data to database (15 mins)

on:
  schedule:
    # Runs "every 15 minutes" (see https://crontab.guru)
    - cron: '*/15 08-18 * * *'
  workflow_dispatch:

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWD: ${{ secrets.DB_PASSWD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
  IQAIR_TOKEN: ${{ secrets.IQAIR_TOKEN }}

jobs:
  build:
    name: Build project for inserting data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate server stub
        run: |
          npm i
          npm run gen-server
          rm -rf node_modules
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: project_package
          path: .
  population:
    name: fetch Population data
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: project_package
          path: .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Fetch and save data to MySQL
        run: python cron_tasks.py generate_population